// <auto-generated />
using System;
using HubVision.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HubVision.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012195217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account_name")
                        .HasComment("Nome da conta de anúncios");

                    b.Property<string>("AdAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad_account_id")
                        .HasComment("ID da conta de anúncios na plataforma (ex: act_123456)");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Data de criação no sistema");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BRL")
                        .HasColumnName("currency")
                        .HasComment("Moeda da conta (ISO 4217)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasComment("Se a conta está ativa no sistema");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasComment("Data da última sincronização com a plataforma");

                    b.Property<Guid>("PlatformAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("status")
                        .HasComment("Status da conta: 1=Active, 2=Disabled, 3=Suspended, 4=Closed");

                    b.Property<string>("TimeZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("time_zone")
                        .HasComment("Fuso horário da conta");

                    b.HasKey("Id")
                        .HasName("pk_ad_account");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_ad_account_client_id");

                    b.HasIndex("PlatformAccountId")
                        .HasDatabaseName("IX_AdAccounts_PlatformAccountId");

                    b.HasIndex("AgencyId", "AdAccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_AdAccounts_AgencyId_AdAccountId");

                    b.HasIndex("AgencyId", "ClientId")
                        .HasDatabaseName("IX_AdAccounts_AgencyId_ClientId");

                    b.HasIndex("AgencyId", "IsActive")
                        .HasDatabaseName("IX_AdAccounts_AgencyId_IsActive");

                    b.ToTable("AdAccount", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccountAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_level");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("TrafficManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traffic_manager_id");

                    b.HasKey("Id")
                        .HasName("pk_ad_account_access");

                    b.HasIndex("AdAccountId")
                        .HasDatabaseName("ix_ad_account_access_ad_account_id");

                    b.HasIndex("GrantedAt")
                        .HasDatabaseName("IX_AdAccountAccess_GrantedAt");

                    b.HasIndex("TrafficManagerId")
                        .HasDatabaseName("ix_ad_account_access_traffic_manager_id");

                    b.HasIndex("AgencyId", "AdAccountId")
                        .HasDatabaseName("IX_AdAccountAccess_AgencyId_AdAccountId");

                    b.HasIndex("AgencyId", "TrafficManagerId")
                        .HasDatabaseName("IX_AdAccountAccess_AgencyId_TrafficManagerId");

                    b.ToTable("AdAccountAccess", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAggregate.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_set_id");

                    b.Property<string>("AdText")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("ad_text");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("CallToAction")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("call_to_action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreativeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creative_id")
                        .HasComment("ID do criativo na plataforma");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Headline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("headline");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("link_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_ad");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Ad_CreatedAt");

                    b.HasIndex("CreativeId")
                        .HasDatabaseName("IX_Ad_CreativeId");

                    b.HasIndex("AdSetId", "Status")
                        .HasDatabaseName("IX_Ad_AdSetId_Status");

                    b.HasIndex("AgencyId", "AdSetId")
                        .HasDatabaseName("IX_Ad_AgencyId_AdSetId");

                    b.HasIndex("AgencyId", "Status")
                        .HasDatabaseName("IX_Ad_AgencyId_Status");

                    b.ToTable("Ad", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdSetAggregate.AdSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("BillingEvent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("billing_event")
                        .HasComment("Evento de cobrança (ex: IMPRESSIONS, LINK_CLICKS)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Data de criação no sistema");

                    b.Property<decimal>("DailyBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("daily_budget")
                        .HasComment("Orçamento diário");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time")
                        .HasComment("Data/hora de término (opcional)");

                    b.Property<decimal?>("LifetimeBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("lifetime_budget")
                        .HasComment("Orçamento vitalício (opcional)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Nome do conjunto de anúncios");

                    b.Property<string>("OptimizationGoal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("optimization_goal")
                        .HasComment("Meta de otimização (ex: CONVERSIONS, LINK_CLICKS)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time")
                        .HasComment("Data/hora de início");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasComment("Status: ACTIVE, PAUSED, DELETED, etc");

                    b.Property<string>("TargetingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("targeting_json")
                        .HasComment("Configuração de segmentação em JSON");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Data da última atualização");

                    b.HasKey("Id")
                        .HasName("pk_ad_set");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_AdSets_CampaignId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AdSets_CreatedAt");

                    b.HasIndex("TargetingJson")
                        .HasDatabaseName("IX_AdSets_TargetingJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TargetingJson"), "gin");

                    b.HasIndex("AgencyId", "CampaignId")
                        .HasDatabaseName("IX_AdSets_AgencyId_CampaignId");

                    b.HasIndex("AgencyId", "Status")
                        .HasDatabaseName("IX_AdSets_AgencyId_Status");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("IX_AdSets_StartTime_EndTime");

                    b.ToTable("AdSet", "HV", t =>
                        {
                            t.HasCheckConstraint("CK_AdSets_DailyBudget_Positive", "\"daily_budget\" >= 0");

                            t.HasCheckConstraint("CK_AdSets_EndTime_After_StartTime", "\"end_time\" IS NULL OR \"end_time\" >= \"start_time\"");

                            t.HasCheckConstraint("CK_AdSets_LifetimeBudget_Positive", "\"lifetime_budget\" IS NULL OR \"lifetime_budget\" >= 0");
                        });
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_agency");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_agency_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_agency_code");

                    b.ToTable("Agency", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.CampaingAggregate.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DailyBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("daily_budget")
                        .HasComment("Orçamento diário");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("LifetimeBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("lifetime_budget")
                        .HasComment("Orçamento vitalício (opcional)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign");

                    b.HasIndex("AdAccountId")
                        .HasDatabaseName("ix_campaign_ad_account_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_campaign_agency_id");

                    b.ToTable("Campaign", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.ClientAggregate.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.HasKey("Id")
                        .HasName("pk_client");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_client_agency_id");

                    b.ToTable("Client", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.ClientAggregate.ClientAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("TrafficManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traffic_manager_id");

                    b.HasKey("Id")
                        .HasName("pk_client_assignments");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_ClientAssignments_AssignedAt");

                    b.HasIndex("TrafficManagerId")
                        .HasDatabaseName("ix_client_assignments_traffic_manager_id");

                    b.HasIndex("AgencyId", "ClientId")
                        .HasDatabaseName("IX_ClientAssignments_AgencyId_ClientId");

                    b.HasIndex("AgencyId", "TrafficManagerId")
                        .HasDatabaseName("IX_ClientAssignments_AgencyId_TrafficManagerId");

                    b.HasIndex("ClientId", "TrafficManagerId")
                        .HasDatabaseName("IX_ClientAssignments_ClientId_TrafficManagerId");

                    b.HasIndex("ClientId", "IsPrimary", "RemovedAt")
                        .HasDatabaseName("IX_ClientAssignments_ClientId_IsPrimary_RemovedAt")
                        .HasFilter("\"removed_at\" IS NULL");

                    b.ToTable("ClientAssignments", (string)null);
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.PlatformAccountAggregate.PlatformAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("access_token");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("platform_email");

                    b.Property<string>("PlatformMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("platform_metadata");

                    b.Property<string>("PlatformUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("platform_user_id");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<Guid>("TrafficManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traffic_manager_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_account");

                    b.HasIndex("PlatformEmail")
                        .HasDatabaseName("IX_PlatformAccounts_PlatformEmail");

                    b.HasIndex("PlatformMetadata")
                        .HasDatabaseName("IX_PlatformAccounts_PlatformMetadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PlatformMetadata"), "gin");

                    b.HasIndex("TrafficManagerId")
                        .HasDatabaseName("IX_PlatformAccounts_TrafficManagerId");

                    b.HasIndex("AgencyId", "TrafficManagerId")
                        .HasDatabaseName("IX_PlatformAccounts_AgencyId_TrafficManagerId");

                    b.HasIndex("Platform", "PlatformUserId")
                        .HasDatabaseName("IX_PlatformAccounts_Platform_PlatformUserId");

                    b.HasIndex("AgencyId", "Platform", "IsActive")
                        .HasDatabaseName("IX_PlatformAccounts_AgencyId_Platform_IsActive");

                    b.ToTable("PlatformAccount", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("HiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hired_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Junior")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_traffic_manager");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_TrafficManagers_Email");

                    b.HasIndex("AgencyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TrafficManagers_AgencyId_Email");

                    b.HasIndex("AgencyId", "IsActive")
                        .HasDatabaseName("IX_TrafficManagers_AgencyId_IsActive");

                    b.HasIndex("AgencyId", "Role")
                        .HasDatabaseName("IX_TrafficManagers_AgencyId_Role");

                    b.ToTable("TrafficManager", "HV");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccount", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdAccounts_Agencies");

                    b.HasOne("HubVision.Domain.AggregatesModel.ClientAggregate.Client", "Client")
                        .WithMany("AdAccounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AdAccounts_Clients");

                    b.HasOne("HubVision.Domain.AggregatesModel.PlatformAccountAggregate.PlatformAccount", "PlatformAccount")
                        .WithMany("AdAccounts")
                        .HasForeignKey("PlatformAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AdAccounts_PlatformAccounts");

                    b.Navigation("Agency");

                    b.Navigation("Client");

                    b.Navigation("PlatformAccount");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccountAccess", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccount", "AdAccount")
                        .WithMany("AdAccountAccesses")
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdAccountAccesses_AdAccounts");

                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ad_account_access_agencies_agency_id");

                    b.HasOne("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", "TrafficManager")
                        .WithMany("AdAccountAccesses")
                        .HasForeignKey("TrafficManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdAccountAccess_TrafficManagers");

                    b.Navigation("AdAccount");

                    b.Navigation("Agency");

                    b.Navigation("TrafficManager");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAggregate.Ad", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AdSetAggregate.AdSet", "AdSet")
                        .WithMany("Ads")
                        .HasForeignKey("AdSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ads_AdSets");

                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ad_Agencies");

                    b.Navigation("AdSet");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdSetAggregate.AdSet", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdSets_Agencies");

                    b.HasOne("HubVision.Domain.AggregatesModel.CampaingAggregate.Campaign", "Campaign")
                        .WithMany("AdSets")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdSets_Campaigns");

                    b.Navigation("Agency");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.CampaingAggregate.Campaign", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccount", "AdAccount")
                        .WithMany("Campaigns")
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Campaigns_AdAccounts");

                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_agency_agency_id");

                    b.Navigation("AdAccount");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.ClientAggregate.Client", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany("Clients")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_agency_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.ClientAggregate.ClientAssignment", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClientAssignments_Agencies");

                    b.HasOne("HubVision.Domain.AggregatesModel.ClientAggregate.Client", "Client")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClientAssignments_Clients");

                    b.HasOne("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", "TrafficManager")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("TrafficManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClientAssignments_TrafficManagers");

                    b.Navigation("Agency");

                    b.Navigation("Client");

                    b.Navigation("TrafficManager");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.PlatformAccountAggregate.PlatformAccount", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlatformAccounts_Agencies");

                    b.HasOne("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", "TrafficManager")
                        .WithMany("PlatformAccounts")
                        .HasForeignKey("TrafficManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlatformAccounts_TrafficManagers");

                    b.Navigation("Agency");

                    b.Navigation("TrafficManager");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", b =>
                {
                    b.HasOne("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", "Agency")
                        .WithMany("TrafficManagers")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TrafficManagers_Agencies");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdAccountAggregate.AdAccount", b =>
                {
                    b.Navigation("AdAccountAccesses");

                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AdSetAggregate.AdSet", b =>
                {
                    b.Navigation("Ads");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.AgencyAggregate.Agency", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("TrafficManagers");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.CampaingAggregate.Campaign", b =>
                {
                    b.Navigation("AdSets");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.ClientAggregate.Client", b =>
                {
                    b.Navigation("AdAccounts");

                    b.Navigation("ClientAssignments");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.PlatformAccountAggregate.PlatformAccount", b =>
                {
                    b.Navigation("AdAccounts");
                });

            modelBuilder.Entity("HubVision.Domain.AggregatesModel.TrafficManagerAggregate.TrafficManager", b =>
                {
                    b.Navigation("AdAccountAccesses");

                    b.Navigation("ClientAssignments");

                    b.Navigation("PlatformAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
